"""v7 deleted the supplier table since it had issues, will be added later

Revision ID: 11ddc8d5afd0
Revises: c1f7567440cf
Create Date: 2020-07-20 08:00:28.774600

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '11ddc8d5afd0'
down_revision = 'c1f7567440cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplier_tb')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_tb',
    sa.Column('ID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('SupplierName', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('Email', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('TelephoneNo', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('Location', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
