"""v5 converted the CustomerTb to have foreign key for areaID

Revision ID: 2626525cbbba
Revises: 4c0ae90675ec
Create Date: 2020-07-19 14:39:29.426820

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2626525cbbba'
down_revision = '4c0ae90675ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_tb', sa.Column('AreaID', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'customer_tb', 'areas_tb', ['AreaID'], ['ID'])
    op.drop_column('customer_tb', 'Area')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_tb', sa.Column('Area', mysql.VARCHAR(length=50), nullable=False))
    op.drop_constraint(None, 'customer_tb', type_='foreignkey')
    op.drop_column('customer_tb', 'AreaID')
    # ### end Alembic commands ###
