"""v6 added ProductID to OrderTb as a foreign key

Revision ID: c1f7567440cf
Revises: 2626525cbbba
Create Date: 2020-07-19 19:35:19.238150

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c1f7567440cf'
down_revision = '2626525cbbba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_tb', sa.Column('ProductID', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'order_tb', 'product_tb', ['ProductID'], ['ID'])
    op.drop_column('order_tb', 'Product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_tb', sa.Column('Product', mysql.VARCHAR(length=50), nullable=False))
    op.drop_constraint(None, 'order_tb', type_='foreignkey')
    op.drop_column('order_tb', 'ProductID')
    # ### end Alembic commands ###
