"""v3-alter table ProductPricesTB, removed description & added ProductTbID

Revision ID: fdf9a02956d1
Revises: c2a8572a8159
Create Date: 2020-07-15 03:53:34.046395

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fdf9a02956d1'
down_revision = 'c2a8572a8159'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_price_tb', sa.Column('ProductTbID', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'product_price_tb', 'product_tb', ['ProductTbID'], ['ID'])
    op.drop_column('product_price_tb', 'Description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_price_tb', sa.Column('Description', mysql.VARCHAR(length=50), nullable=False))
    op.drop_constraint(None, 'product_price_tb', type_='foreignkey')
    op.drop_column('product_price_tb', 'ProductTbID')
    # ### end Alembic commands ###
